/**
 * Created by chernikovalexey on 18/09/17.
 */

(function (undefined) {

    // for commented currencies, ECB does not provide any data on conversion rates
    const CURRENCIES = {
        //"ALL": "Lek",
        //"AWG": "ƒ",
        "AUD": "$",
        //"AZN": "ман",
        //"BSD": "$",
        //"BBD": "$",
        //"BZD": "BZ$",
        //"BMD": "$",
        //"BAM": "KM",
        //"BWP": "P",
        //"BGN": "лв",
        "BRL": "R$",
        //"BND": "$",
        //"KHR": "៛",
        "CAD": "$",
        //"KYD": "$",
        "CNY": "¥",
        //"COP": "$",
        "HRK": "kn",
        "CZK": "Kč",
        "DKK": "kr",
        //"DOP": "RD$",
        //"XCD": "$",
        //"EGP": "£",
        //"SVC": "$",
        "EUR": "€",
        //"FKP": "£",
        //"FJD": "$",
        //"GIP": "£",
        //"GTQ": "Q",
        //"GYD": "$",
        //"HNL": "L",
        "HKD": "$",
        "HUF": "Ft",
        //"ISK": "kr",
        "INR": "INR",
        //"IDR": "Rp",
        //"ILS": "₪",
        //"JMD": "J$",
        //"KZT": "₸",
        //"KGS": "сом",
        //"LAK": "₭",
        //"LBP": "£",
        //"LRD": "$",
        //"MKD": "ден",
        //"MYR": "RM",
        //"MUR": "₨",
        //"MXN": "$",
        //"MNT": "₮",
        //"MZN": "MT",
        //"NAD": "$",
        //"NPR": "₨",
        //"ANG": "ƒ",
        "NZD": "$",
        //"NIO": "C$",
        //"NGN": "₦",
        //"NOK": "kr",
        //"PKR": "₨",
        //"PAB": "B/.",
        //"PEN": "S/.",
        //"PHP": "₱",
        "PLN": "zł",
        //"QAR": "﷼",
        //"RON": "lei",
        "RUB": "руб",
        //"SHP": "£",
        //"SAR": "﷼",
        //"RSD": "Дин.",
        //"SCR": "₨",
        "SGD": "$",
        //"SBD": "$",
        //"SOS": "S",
        "ZAR": "R",
        //"LKR": "₨",
        "SEK": "kr",
        "CHF": "CHF",
        //"SRD": "$",
        //"TWD": "NT$",
        //"THB": "฿",
        //"TTD": "TT$",
        //"TRY": "TRY",
        //"UAH": "₴",
        "GBP": "£",
        "USD": "$"
        //"UYU": "$U",
        //"UZS": "сўм",
        //"YER": "﷼"
    };

    // if country's currency is not supported, users from there are charged in USD
    const C2C = {
        "AF": "USD",
        "AX": "EUR",
        "AL": "USD",
        "DZ": "USD",
        "AS": "USD",
        "AD": "EUR",
        "AO": "USD",
        "AI": "USD",
        "AQ": "AUD",
        "AG": "USD",
        "AR": "USD",
        "AM": "USD",
        "AW": "USD",
        "AU": "AUD",
        "AT": "EUR",
        "AZ": "USD",
        "BS": "USD",
        "BH": "USD",
        "BD": "USD",
        "BB": "USD",
        "BY": "USD",
        "BE": "EUR",
        "BZ": "USD",
        "BJ": "USD",
        "BM": "USD",
        "BT": "USD",
        "BO": "USD",
        "BQ": "USD",
        "BA": "USD",
        "BW": "USD",
        "BV": "NOK",
        "BR": "BRL",
        "IO": "USD",
        "UM": "USD",
        "VG": "USD",
        "VI": "USD",
        "BN": "USD",
        "BG": "BGN",
        "BF": "USD",
        "BI": "USD",
        "KH": "USD",
        "CM": "USD",
        "CA": "CAD",
        "CV": "USD",
        "KY": "USD",
        "CF": "USD",
        "TD": "USD",
        "CL": "USD",
        "CN": "CNY",
        "CX": "AUD",
        "CC": "AUD",
        "CO": "USD",
        "KM": "USD",
        "CG": "USD",
        "CD": "USD",
        "CK": "NZD",
        "CR": "USD",
        "HR": "HRK",
        "CU": "USD",
        "CW": "USD",
        "CY": "EUR",
        "CZ": "CZK",
        "DK": "DKK",
        "DJ": "USD",
        "DM": "USD",
        "DO": "USD",
        "EC": "USD",
        "EG": "USD",
        "SV": "USD",
        "GQ": "USD",
        "ER": "USD",
        "EE": "EUR",
        "ET": "USD",
        "FK": "USD",
        "FO": "DKK",
        "FJ": "USD",
        "FI": "EUR",
        "FR": "EUR",
        "GF": "EUR",
        "PF": "USD",
        "TF": "EUR",
        "GA": "USD",
        "GM": "USD",
        "GE": "USD",
        "DE": "EUR",
        "GH": "USD",
        "GI": "USD",
        "GR": "EUR",
        "GL": "DKK",
        "GD": "USD",
        "GP": "EUR",
        "GU": "USD",
        "GT": "USD",
        "GG": "GBP",
        "GN": "USD",
        "GW": "USD",
        "GY": "USD",
        "HT": "USD",
        "HM": "AUD",
        "VA": "EUR",
        "HN": "USD",
        "HK": "HKD",
        "HU": "HUF",
        "IS": "USD",
        "IN": "INR",
        "ID": "IDR",
        "CI": "USD",
        "IR": "USD",
        "IQ": "USD",
        "IE": "EUR",
        "IM": "GBP",
        "IL": "ILS",
        "IT": "EUR",
        "JM": "USD",
        "JP": "USD",
        "JE": "GBP",
        "JO": "USD",
        "KZ": "USD",
        "KE": "USD",
        "KI": "AUD",
        "KW": "USD",
        "KG": "USD",
        "LA": "USD",
        "LV": "EUR",
        "LB": "USD",
        "LS": "USD",
        "LR": "USD",
        "LY": "USD",
        "LI": "CHF",
        "LT": "EUR",
        "LU": "EUR",
        "MO": "USD",
        "MK": "USD",
        "MG": "USD",
        "MW": "USD",
        "MY": "MYR",
        "MV": "USD",
        "ML": "USD",
        "MT": "EUR",
        "MH": "USD",
        "MQ": "EUR",
        "MR": "USD",
        "MU": "USD",
        "YT": "EUR",
        "MX": "MXN",
        "FM": "USD",
        "MD": "USD",
        "MC": "EUR",
        "MN": "USD",
        "ME": "EUR",
        "MS": "USD",
        "MA": "USD",
        "MZ": "USD",
        "MM": "USD",
        "NA": "USD",
        "NR": "AUD",
        "NP": "USD",
        "NL": "EUR",
        "NC": "USD",
        "NZ": "NZD",
        "NI": "USD",
        "NE": "USD",
        "NG": "USD",
        "NU": "NZD",
        "NF": "AUD",
        "KP": "USD",
        "MP": "USD",
        "NO": "NOK",
        "OM": "USD",
        "PK": "USD",
        "PW": "USD",
        "PS": "ILS",
        "PA": "USD",
        "PG": "USD",
        "PY": "USD",
        "PE": "USD",
        "PH": "PHP",
        "PN": "NZD",
        "PL": "PLN",
        "PT": "EUR",
        "PR": "USD",
        "QA": "USD",
        "XK": "EUR",
        "RE": "EUR",
        "RO": "RON",
        "RU": "RUB",
        "RW": "USD",
        "BL": "EUR",
        "SH": "USD",
        "KN": "USD",
        "LC": "USD",
        "MF": "EUR",
        "PM": "EUR",
        "VC": "USD",
        "WS": "USD",
        "SM": "EUR",
        "ST": "USD",
        "SA": "USD",
        "SN": "USD",
        "RS": "USD",
        "SC": "USD",
        "SL": "USD",
        "SG": "USD",
        "SX": "USD",
        "SK": "EUR",
        "SI": "EUR",
        "SB": "USD",
        "SO": "USD",
        "ZA": "ZAR",
        "GS": "GBP",
        "KR": "USD",
        "SS": "USD",
        "ES": "EUR",
        "LK": "USD",
        "SD": "USD",
        "SR": "USD",
        "SJ": "NOK",
        "SZ": "USD",
        "SE": "SEK",
        "CH": "CHF",
        "SY": "USD",
        "TW": "USD",
        "TJ": "USD",
        "TZ": "USD",
        "TH": "THB",
        "TL": "USD",
        "TG": "USD",
        "TK": "NZD",
        "TO": "USD",
        "TT": "USD",
        "TN": "USD",
        "TR": "TRY",
        "TM": "USD",
        "TC": "USD",
        "TV": "AUD",
        "UG": "USD",
        "UA": "USD",
        "AE": "USD",
        "GB": "GBP",
        "US": "USD",
        "UY": "USD",
        "UZ": "USD",
        "VU": "USD",
        "VE": "USD",
        "VN": "USD",
        "WF": "USD",
        "EH": "USD",
        "YE": "USD",
        "ZM": "USD",
        "ZW": "USD"
    };

    pl.extend(ke.ext.money, {
        currencyCodeToSymbol: function (code) {
            return CURRENCIES[code] || code;
        },

        getCurrencyForCountryCode: function (cc) {
            return C2C[cc] || 'USD';
        },

        updateCurrencyRates: function (callback) {
            $.ajax({
                url: 'https://api.fixer.io/latest',
                type: 'GET',
                dataType: 'JSON',
                data: {
                    base: 'EUR'
                },
                success: function (r) {
                    if (r.rates) {
                        ke.ext.util.storageUtil.setVal('conversion_rates', JSON.stringify(
                            r.rates
                        ));

                        if (callback) callback();
                    }
                }
            });
        }
    });

})();